### PR TITLE
Active Tab 

### PR DESCRIPTION
**Pull request by sarinali**
# Description

This will check if the current tab is highlighted, this is done by checking the `visibility` attribute. Upon selecting tab, only the selected tab will have this attribute while the others do not. Also verified that selected tabs have the css property 'color': rgb(12, 12, 13) while the unselected ones are 'color': rgb(21, 20, 26). So we verify that visibility prop is there and also the colours match up.

## Bugzilla bug ID

**ID:** 1895904
**Link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1895904

## Type of change

Please delete options that are not relevant.

- [x] New Test

# How does this resolve / make progress on that bug?

finishes

# Screenshots / Explanations

N/A

# Comments / Concerns

I hope this method of verification is satisfactory!

### CODE REVIEW

**Review by ben-c-at-moz — CHANGES_REQUESTED** [review]
Sadly, the test fails in dark mode: `AssertionError: assert ('rgb(251, 251, 254)' == 'rgb(12, 12, 13)'`

I also think it should be called `test_active_tab` rather than `test_active_test`.

**Comment by sarinali** [comment]
> Sadly, the test fails in dark mode: `AssertionError: assert ('rgb(251, 251, 254)' == 'rgb(12, 12, 13)'`
> 
> I also think it should be called `test_active_tab` rather than `test_active_test`.

i had a lapse in naming capabilities earlier

**Comment by sarinali** [comment]
> Sadly, the test fails in dark mode: `AssertionError: assert ('rgb(251, 251, 254)' == 'rgb(12, 12, 13)'`
> 
> I also think it should be called `test_active_tab` rather than `test_active_test`.

ok so i removed the css value checking, the reason for this is because i went and investigated the colour it should be in dark mode, the colour does not change. in fact, the css between selected and unselected is the same for the tab item, i verified that the `visuallyselected` field works by doing some experimental code checking if an unselected tab has that prop. it does not. so i think this is a valid way to verify. what do you think?

**Review by ben-c-at-moz — APPROVED** [review]
I do think the attribute is a fine way to do the test. Ready to merge.

**Pull request merged**
