### PR TITLE
Onboarding Task 

### PR DESCRIPTION
**Pull request by sarinali**
Completed the onboarding task using existing methods and files. 

https://docs.google.com/document/d/1_uhLyTmUrPrldKUigGR0zQetk4PxQZQD5i5sCBlhSyE/edit

### CODE REVIEW

**Comment by ben-c-at-moz** [comment]
Ok, not exactly what I was looking for. Maybe the instructions could have been clearer, but we need to exercise specific elements of the AwesomeBar dropdown, shown in this image. They do already exist in the element manifest JSON though!
Screenshot 2024-05-12 at 15 46 47

**Review by ben-c-at-moz — CHANGES_REQUESTED** [review]
You clearly learned how the repo works, but perhaps I needed to clarify the instructions. I left a comment to point you in the right direction, reach out if you need more help.

**Comment by sarinali** [comment]
> Ok, not exactly what I was looking for. Maybe the instructions could have been clearer, but we need to exercise specific elements of the AwesomeBar dropdown, shown in this image. They do already exist in the element manifest JSON though! You will need to write a short new test, because the type+TAB method doesn't click those elements.
> Screenshot 2024-05-12 at 15 46 47

sorry!! I fixed it now, hope this works.

**Review by ben-c-at-moz — CHANGES_REQUESTED** [review]
Awesome, no notes. Fully passed off this task. Set to RC because we're not merging the task code.

**Comment by ben-c-at-moz** [comment]
Thanks for participating!

**Pull request closed without merging**
