### PR TITLE
As/addon suggestion based on search input

### PR DESCRIPTION
**Pull request by soncuteanca**
# Description

This test ensures that a matching add-on suggestion appears based on the search input and that clicking on the suggested add-on redirects to the corresponding add-on page.

## Bugzilla bug ID

**ID: 1902787**
**Link: https://bugzilla.mozilla.org/show_bug.cgi?id=1902787**

## Type of change

Please delete options that are not relevant.

- [x ] New Test

# How does this resolve / make progress on that bug?
In progress

Please describe the progress or significance with respect to the bug listed above.

# Screenshots / Explanations

Please upload any relevant media or add a relevant description with respect to the bug listed above.

# Comments / Concerns
I have a passing test, but I need to work on optimizing the timing. None of the waiting condition approach I've tried so far did the trick.

Please add a short blurb about any comments or concerns that this change might cause.

### CODE REVIEW

**Comment by ben-c-at-moz** [comment]
I made some suggested changes (and one BOM method that turned out not to be helpful this time but may be helpful in future), in the branch bc/amendments-to-82. @Tracy-Walker pointed out to me that this might be a good time not to parametrize since we have to wait every time the browser starts. I also made it wait only as long as it needed to before proceeding (sort of).

**Review by ben-c-at-moz — CHANGES_REQUESTED** [review]
If you get a moment to de-parametrize this, I think that would make it nicer for us to run. Also, I think you only need to wait 10 seconds after clicking the url bar, but that may be wrong. If you try it and it doesn't work, that's fine.

**Comment by soncuteanca** [comment]
I've de-parameterized the test. However, I have poor internet connection since yesterday, the test only completes successfully in 40 seconds. As a result, I need both time.sleep statements to remain in place.

**Review by ben-c-at-moz — APPROVED** [review]
I've added a marker to the test to indicate that it's slow, and we'll come back to it when we optimize tests later.

**Pull request merged**
